maintainer       "Leonid"
maintainer_email "agoddard@mbl.edu"
license           "Apache 2.0"
description      "Installs/Configures Jira+Logstash+Elasticsearch+Kibana"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends           "java"
depends           "jira"
depends           "logstash"
depends           "elasticsearch"
